name: CI/CD Pipeline
on:
  push:
    branches: 
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: acenawaz01/UnitConversion
