name: CI/CD Pipeline
on:
  push:
    branches: 
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: acenawaz01/UnitConversion
      - name: Zipping the artifact
        uses: vimtor/action-zip@v1
        with:
          files: .
          recursive: true
          dest: artifact.zip 
          path: ${{ github.workspace }}/artifact.zip
